version: '3.7'

networks:
  my-moments:
    driver: bridge
    name: my-moments
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  discovery-service:
    restart: on-failure
    build:
      context: ../
      dockerfile: discovery-service/Dockerfile-dev
    networks:
      - my-moments
    ports:
      - 8761:8761
    volumes:
      - /discovery-service/dir:/app
    container_name: discovery-service

  configuration-service:
    restart: on-failure
    build:
      context: ../
      dockerfile: configuration-service/Dockerfile-dev
    networks:
      - my-moments
    ports:
      - 8888:8888
    volumes:
      - /configuration-service/dir:/app
    container_name: configuration-service

  vault-server:
    image: vault:1.8.1
    restart: on-failure
    ports:
      - 8200:8200
    networks:
      my-moments:
        ipv4_address: 172.21.0.10
        aliases:
          - vault-server
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-token"
    cap_add:
      - IPC_LOCK
    container_name: vault-server

  vault-client:
    build:
      context: ../
      dockerfile: vault-client/Dockerfile-dev
    restart: on-failure
    networks:
      my-moments:
        ipv4_address: 172.21.0.20
        aliases:
          - vault-client
    environment:
      VAULT_ADDR: "http://vault-server:8200"
    container_name: vault-client

  mongo-db-comment-service:
    image: mongo:3.6
    networks:
      - my-moments
    ports:
      - 27021:27017
    volumes:
      - ./data/db:/data/db
    container_name: mongo-db-comment-service

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - my-moments
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: my-moments-user
      RABBITMQ_DEFAULT_PASS: my-moments-password
    ports:
      - 5672:5672
      - 15672:15672