version: '3.7'

services:
  configuration-service:
    restart: on-failure
    build:
      context: ../configuration-service
      dockerfile: Dockerfile
    image: configuration-service:latest
    ports:
      - 8888:8888
    volumes:
      - /configuration-service/dir:/app
    container_name: configuration-service

  mongo-db-comment-service:
    image: mongo:3.6
    ports:
      - 27021:27017
    volumes:
      - ./data/db:/data/db
    container_name: mongo-db-comment-service
