#
# Eureka
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.99.100:8761/eureka/
#  instance:
#    preferIpAddress: true
#
# Spring Boot Actuator
#
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  security:
#    enabled: false
##
## Custom properties
##
#my-moments:
#  #
#  # Swagger
#  #
#  swagger:
#    authorization-header: Authorization
#    contact-email: https://github.com/NowakArtur97
#    contact-name: Artur Nowak
#    contact-url: https://github.com/NowakArtur97
#    description: REST API of the social network
#    license: MIT
#    license-url: https://github.com/NowakArtur97/MyMoments/blob/master/LICENSE
#    path-selectors: /api/**
#    terms-of-serviceUrl: https://github.com/NowakArtur97/MyMoments/blob/master/LICENSE
#    title: MyMoments
#    version: 1.0
#  #
#  # JWT
#  #
#  jwt:
#    secretKey: secret
#    validity: 36000000
#    authenticated-ant-matchers: /api/v1/**
#    ignored-endpoints:
#      - /v2/api-docs
#      - /configuration/ui
#      - /swagger-resources
#      - /configuration/security
#      - /swagger-ui/
#      - /webjars
#    ignored-ant-matchers:
#      - /v2/api-docs
#      - /configuration/ui
#      - /swagger-resources/**
#      - /configuration/security
#      - /swagger-ui/**
#      - /webjars/**
#    authorization-header: Authorization
#    authorization-type: Bearer
#    authorization-header-length: 7