version: '3.7'

networks:
  my-moments:
    driver: bridge
    name: my-moments

services:
  configuration-service:
    restart: on-failure
    build: ./configuration-service
    networks:
      - my-moments
    container_name: configuration-service
    ports:
      - 8888:8888
    volumes:
      - /configuration-service/dir:/app

  discovery-service:
    restart: on-failure
    build: ./discovery-service
    networks:
      - my-moments
    container_name: discovery-service
    ports:
      - 8761:8761
    volumes:
      - /discovery-service/dir:/app
    depends_on:
      - configuration-service

#  user-service:
#    restart: on-failure
#    build: ./user-service
#    networks:
#      - my-moments
#    container_name: user-service
#    ports:
#      - 8081:8081
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#    volumes:
#      - /user-service/dir:/app
#    depends_on:
#      - discovery-service
#      - mongo-db-user-service
#      - rabbitmq
#
#  post-service:
#    restart: on-failure
#    build: ./post-service
#    networks:
#      - my-moments
#    container_name: post-service
#    ports:
#      - 8082:8082
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#    volumes:
#      - /post-service/dir:/app
#    depends_on:
#      - user-service
#      - mongo-db-post-service
#
#  comment-service:
#    restart: on-failure
#    build: ./comment-service
#    networks:
#      - my-moments
#    container_name: comment-service
#    ports:
#      - 8083:8083
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#    volumes:
#      - /comment-service/dir:/app
#    depends_on:
#      - post-service
#      - mongo-db-comment-service

  mongo-db-user-service:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongo-db-uesr-service:/data/db
    networks:
      - my-moments
    container_name: mongo-db-user-service

  mongo-db-post-service:
    image: mongo:3.6
    ports:
      - 27019:27017
    volumes:
      - /var/lib/mongo-db-post-service:/data/db
    networks:
      - my-moments
    container_name: mongo-db-post-service

  mongo-db-comment-service:
    image: mongo:3.6
    ports:
      - 27021:27017
    volumes:
      - /var/lib/mongo-db-comment-service:/data/db
    networks:
      - my-moments
    container_name: mongo-db-comment-service

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - my-moments
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: my-moments-user
      RABBITMQ_DEFAULT_PASS: my-moments-password
    ports:
      - 5672:5672
      - 15672:15672
