version: '3.7'

networks:
  my-moments:
    driver: bridge
#    external: false
    name: my-moments

services:
  discovery-service:
    restart: on-failure
    build: ./discovery-service
    networks:
      - my-moments
    container_name: discovery-service
    ports:
      - 8761:8761
    volumes:
      - /discovery-service/dir:/app

  user-service:
    restart: on-failure
    build: ./user-service
    networks:
      - my-moments
    container_name: user-service
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - /user-service/dir:/app
    depends_on:
      - discovery-service
      - mongo-db-user-service

  mongo-db-user-service:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongo-db-uesr-service:/data/db
    networks:
      - my-moments
    container_name: mongo-db-user-service

  mongo-db-post-service:
    image: mongo:3.6
    ports:
      - 27019:27017
    volumes:
      - /var/lib/mongo-db-post-service:/data/db
    networks:
      - my-moments
    container_name: mongo-db-post-service