#
# Spring
#
spring:
  #
  # Mongo DB
  #
  data:
    mongodb:
      database: my-moments-user-service
      host: localhost
      port: 27017
#
# Eureka
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/