#
# Spring
#
spring:
  #
  # Mongo DB
  #
  data:
    mongodb:
      database: my-moments-user-service
      host: 192.168.99.100
      port: 27017
  #
  # Messaging / RabbitMQ
  #
  cloud:
    stream:
      bindings:
        userUpdateChannel:
          destination: user.update
          contentType: application/json
        userDeleteChannel:
          destination: user.delete
          contentType: application/json
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: my-moments-user
    password: my-moments-password