spring:
  #
  # Mongo DB
  #
  data:
    mongodb:
      posts:
        database: my-moments-post-service
        uri: mongodb://192.168.99.100:27019/mongo-db-post-service
      users:
        database: my-moments-user-service
        uri: mongodb://192.168.99.100:27017/mongo-db-user-service
  #
  # Messaging
  #
  cloud:
    stream:
      bindings:
        userUpdateChannel:
          destination: user.update
          contentType: application/json
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: my-moments-user
    password: my-moments-password