spring:
  #
  # Mongo DB
  #
  data:
    mongodb:
      comments:
        database: my-moments-post-service
        uri: mongodb://192.168.99.100:27019/mongo-db-post-service
      users:
        database: my-moments-user-service
        uri: mongodb://192.168.99.100:27017/mongo-db-user-service
