#
# Spring
#
spring:
  application:
    name: post-service
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}
  #
  # Messaging
  #
  cloud:
    stream:
      rabbit:
        binder:
          brokers: 192.168.99.100:15672
        bindings:
          momentsPostChanged:
            consumer:
              startOffset: latest
              autoCommitOffset: false
            content-type: application/json
      bindings:
        momentsPostChanged:
          destination: moments.post.changed
          contentType: application/json
          group: graphService
          consumer:
            startOffset: latest
            autoCommitOffset: false
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: my-moments-user
    password: my-moments-password
#
# Eureka
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
  instance:
    preferIpAddress: true
#
# Server
#
server:
  port: 8082
#
# Spring Boot Actuator
#
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
#
# Custom properties
#
my-moments:
  #
  # Swagger
  #
  swagger:
    authorization-header: Authorization
    contact-email: https://github.com/NowakArtur97
    contact-name: Artur Nowak
    contact-url: https://github.com/NowakArtur97
    description: REST API of the social network
    license: MIT
    license-url: https://github.com/NowakArtur97/MyMoments/blob/master/LICENSE
    path-selectors: /api/**
    terms-of-serviceUrl: https://github.com/NowakArtur97/MyMoments/blob/master/LICENSE
    title: MyMoments
    version: 1.0
  #
  # JWT
  #
  jwt:
    secretKey: secret
    validity: 36000000
    authenticated-ant-matchers: /api/v1/**
    ignored-endpoints:
      - /v2/api-docs
      - /configuration/ui
      - /swagger-resources
      - /configuration/security
      - /swagger-ui/
      - /webjars
    ignored-ant-matchers:
      - /v2/api-docs
      - /configuration/ui
      - /swagger-resources/**
      - /configuration/security
      - /swagger-ui/**
      - /webjars/**
    authorization-header: Authorization
    authorization-type: Bearer
    authorization-header-length: 7