version: '2.4'

networks:
  my-moments:
    driver: bridge
    name: my-moments
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  follower-service:
    restart: on-failure
    build:
      context: .
    networks:
      - my-moments
    ports:
      - "8084:8084"
    volumes:
      - /follower-service/dir:/app
    depends_on:
      - configuration-service
      - neo4j
    container_name: follower-service
    cpus: 0.5
    mem_limit: 256M
    mem_reservation: 64M

  configuration-service:
    restart: on-failure
    networks:
      - my-moments
    build:
      context: ../configuration-service
      dockerfile: Dockerfile
    image: configuration-service:latest
    ports:
      - "8888:8888"
    volumes:
      - /configuration-service/dir:/app
    container_name: configuration-service
    cpus: 0.5
    mem_limit: 256M
    mem_reservation: 64M

  neo4j:
    restart: always
    image: neo4j:4.3.3
    networks:
      - my-moments
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/secret
      - NEO4J_dbms_memory_pagecache_size=128MB
      - NEO4J_dbms.memory.heap.initial_size=128MB
      - NEO4J_dbms_memory_heap_max__size=128MB
    ports:
      - "7474:7474"
      - "7687:7687"
    container_name: neo4j
    cpus: 0.5
    mem_limit: 256M
    mem_reservation: 64M
