#
# Eureka
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
  instance:
    preferIpAddress: true
spring:
  #
  # RabbitMQ
  #
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: my-moments-user
    password: my-moments-password