#
# Spring
#
spring:
  application:
    name: configuration-service
#  #
#  # Config Server
#  #
#  cloud:
#    config:
#      server:
#        token: vault-plaintext-root-token
#        vault:
#          application-name: configuration-service
#          host: 192.168.99.100
#          scheme: http
#          token: vault-plaintext-root-token
#          authentication: TOKEN
#          order: 1
#          skip-ssl-validation: true
#          kv-version: 2
#          kv:
#            enabled: true
#            backend: secret
#            profile-separator: '/'
#            default-context: configuration-service
#            application-name: configuration-service
#      allow-override: true
#      override-none: true
#      override-system-properties: false
#
# Spring Boot Actuator
#
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
#
# Custom properties
#
my-moments:
  default-user-role: USER_ROLE
  admin-role: ADMIN_ROLE
  #
  # Swagger
  #
  swagger:
    authorization-header: Authorization
    contact-email: https://github.com/NowakArtur97
    contact-name: Artur Nowak
    contact-url: https://github.com/NowakArtur97
    description: REST API of the social network
    license: MIT
    license-url: https://github.com/NowakArtur97/MyMoments/blob/master/LICENSE
    path-selectors: /api/**
    terms-of-serviceUrl: https://github.com/NowakArtur97/MyMoments/blob/master/LICENSE
    title: MyMoments
    version: 1.0
  #
  # JWT
  #
  jwt:
#    secretKey: ${secretKey} # already in vault
    validity: 72000000
    authenticated-ant-matchers: /api/v1/**
    ignored-endpoints:
      - /v2/api-docs
      - /configuration/ui
      - /swagger-resources
      - /configuration/security
      - /swagger-ui.html
      - /swagger-ui/
      - /webjars
    ignored-ant-matchers:
      - /v2/api-docs
      - /configuration/ui
      - /swagger-resources/**
      - /configuration/security
      - /swagger-ui.html
      - /swagger-ui/**
      - /webjars/**
    authorization-header: Authorization
    authorization-type: Bearer
    authorization-header-length: 7