#
# Eureka
#
eureka:
  client:
    enabled: false
spring:
  #
  # RabbitMQ
  #
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: my-moments-user
    password: my-moments-password
  #
  # Zipkin
  #
  zipkin:
    enabled: false
  #
  # Sleuth
  #
  sleuth:
    enabled: false
#
# Custom properties
#
my-moments:
  #
  # JWT / properties when Vault is disabled
  #
  jwt:
    secret-key: topSecret