spring:
  #
  # Multipart
  #
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 15MB
  #
  # Mongo DB
  #
  data:
    mongodb:
      database: my-moments-post-service
      host: 192.168.99.100
      port: 27019
  #
  # Messaging
  #
  cloud:
    stream:
      bindings:
        userUpdateChannel:
          destination: user.update
          contentType: application/json
        userDeleteChannel:
          destination: user.delete
          contentType: application/json
        postDeleteChannel:
          destination: post.delete
          contentType: application/json
