spring:
  #
  # Mongo DB
  #
  data:
    mongodb:
      database: my-moments-user-service
      host: 192.168.99.100
      port: 27017
  #
  # Messaging
  #
  cloud:
    stream:
      bindings:
        userUpdateChannel:
          destination: user.update
          contentType: application/json
        userDeleteChannel:
          destination: user.delete
          contentType: application/json
  #
  # Custom properties
  #
my-moments:
  #
  # JWT
  #
  jwt:
    ignored-endpoints:
      - /registration
      - /authentication
      - /v2/api-docs
      - /configuration/ui
      - /swagger-resources
      - /configuration/security
      - /swagger-ui.html
      - /swagger-ui/
      - /webjars
    ignored-ant-matchers:
      - /api/v1/registration/**
      - /api/v1/authentication/**
      - /v2/api-docs
      - /configuration/ui
      - /swagger-resources/**
      - /configuration/security
      - /swagger-ui.html
      - /swagger-ui/
      - /webjars/**