version: '2.4'

networks:
  my-moments:
    driver: bridge
    name: my-moments
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  user-service:
    restart: on-failure
    build:
      context: .
    networks:
      - my-moments
    ports:
      - "8081:8081"
    volumes:
      - /user-service/dir:/app
    depends_on:
      - configuration-service
      - mongo-db-user-service
    container_name: user-service
    cpus: 0.5
    mem_limit: 256M
    mem_reservation: 64M

  configuration-service:
    restart: on-failure
    networks:
      - my-moments
    build:
      context: ../configuration-service
      dockerfile: Dockerfile
    image: configuration-service:latest
    ports:
      - "8888:8888"
    volumes:
      - /configuration-service/dir:/app
    container_name: configuration-service
    cpus: 0.5
    mem_limit: 256M
    mem_reservation: 64M

  mongo-db-user-service:
    image: mongo:3.6
    networks:
      - my-moments
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    container_name: mongo-db-user-service
    cpus: 0.5
    mem_limit: 256M
    mem_reservation: 64M
