version: '3.7'

services:
  configuration-service:
    restart: on-failure
    build:
      context: ../
      dockerfile: configuration-service/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - /configuration-service/dir:/app
    container_name: configuration-service

  mongo-db-user-service:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    container_name: mongo-db-user-service
