version: '3.7'

networks:
  my-moments:
    driver: bridge
    name: my-moments
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  mongo-db-user-service:
    image: mongo:3.6
    networks:
      - my-moments
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  configuration-service:
    restart: on-failure
    build:
      context: ../
      dockerfile: configuration-service/Dockerfile-dev
    networks:
      - my-moments
    container_name: configuration-service
    ports:
      - 8888:8888
    volumes:
      - /configuration-service/dir:/app

  vault-server:
    image: vault:1.8.1
    restart: on-failure
    ports:
      - 8200:8200
    networks:
      my-moments:
        ipv4_address: 172.21.0.10
        aliases:
          - vault-server
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK

  vault-client:
    build:
      context: ../
      dockerfile: vault-client/Dockerfile-dev
    restart: on-failure
    networks:
      my-moments:
        ipv4_address: 172.21.0.20
        aliases:
          - vault-client
    environment:
      VAULT_ADDR: "http://vault-server:8200"