version: '2.4'

networks:
  my-moments:
    driver: bridge
    name: my-moments
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  discovery-service:
    restart: on-failure
    build:
      context: ../discovery-service
      dockerfile: Dockerfile
    networks:
      - my-moments
    ports:
      - "8761:8761"
    volumes:
      - /discovery-service/dir:/app
    container_name: discovery-service
    cpus: 0.5
    mem_limit: 256M
    mem_reservation: 64M

  configuration-service:
    restart: on-failure
    build:
      context: ../configuration-service
      dockerfile: Dockerfile
    image: configuration-service:latest
    networks:
      - my-moments
    ports:
      - "8888:8888"
    volumes:
      - /configuration-service/dir:/app
    container_name: configuration-service
    cpus: 0.5
    mem_limit: 256M
    mem_reservation: 64M

  vault-server:
    image: vault:1.8.1
    restart: on-failure
    ports:
      - "8200:8200"
    networks:
      my-moments:
        ipv4_address: 172.21.0.10
        aliases:
          - vault-server
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "token"
    cap_add:
      - IPC_LOCK
    container_name: vault-server
    cpus: 0.5
    mem_limit: 128M
    mem_reservation: 32M

  vault-client:
    build:
      context: ../
      dockerfile: vault-client/Dockerfile-dev
    restart: on-failure
    networks:
      my-moments:
        ipv4_address: 172.21.0.20
        aliases:
          - vault-client
    environment:
      VAULT_ADDR: "http://vault-server:8200"
    container_name: vault-client
    cpus: 0.5
    mem_limit: 128M
    mem_reservation: 32M

  mongo-db-user-service:
    image: mongo:3.6
    networks:
      - my-moments
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    container_name: mongo-db-user-service
    cpus: 0.5
    mem_limit: 256M
    mem_reservation: 64M

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - my-moments
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: my-moments-user
      RABBITMQ_DEFAULT_PASS: my-moments-password
    ports:
      - "5672:5672"
      - "15672:15672"
    cpus: 0.5
    mem_limit: 128M
    mem_reservation: 32M
